### ISSUE TITLE
Stimulus 3.0 compatibility.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-fields#2]

**Comment by pascallaliberte** [comment]
Advanced on this, but it's tricky with microbundle.

Updating to `@hotwired/stimulus@^3.0.1` produces this error in the browser from a bad compilation:

```
Uncaught (in promise) TypeError: Class constructor Controller cannot be invoked without 'new'
```

See https://github.com/rails/webpacker/issues/3153

**Comment by pascallaliberte** [comment]
I considered moving away from a babel-based (microbundle) package helper to an esbuild-based (nanobundle) package helper, but that produced errors also.

I think I have to dig into babel stuff.

@andrewculver Since this is not a simple quick fix, I'll leave the call to you to pursue this further or leave it around until maybe I catch an epiphany.

**Comment by pascallaliberte** [comment]
The trick is to tell `microbundle` to not target IE11:

```json
  "browserslist": [
    "defaults",
    "not IE 11"
  ]
```

See https://github.com/hotwired/stimulus/issues/433#issuecomment-956601114
