### ISSUE TITLE
Add columns to `options`.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-fields#21]
Currently working on a form where the "options" presented could number in the dozens. When this is the case, I would love for the field to have the option of automatically breaking itself up into two or three columns, although remaining responsively in one column on mobile, etc.

**Comment by pascallaliberte** [comment]
In the absence of container queries to determine how many columns to be displayed, there are alternative solutions using grid of flex. Will pick the right approach from [this article on container query solutions with css grid or flexbox](https://moderncss.dev/container-query-solutions-with-css-grid-and-flexbox/).

**Comment by pascallaliberte** [comment]
Actually, container queries and such won't be too great because we'll have to "bin" in advance the options into different divs.

e.g. for 23 options and max 3 columns, div1 will have 8 options, div2 will have 8 options, and div3 will have 7 options.

That's not so bad, it's just that in the event where 2 columns are shown, the options will end up being laid out as such:

```
div1(1-8)  | div2(9-16)
-----------
div3(17-23)
```

Whereas it should be laid out as such (for two columns):

```
(1-12) | (13-23)
```

And in the case where each option is not of equal height, it might end up that col1 shows 10 options and col2 shows 13 options.

Luckily, that's a job for CSS columns.

See [Columns - Tailwind CSS](https://tailwindcss.com/docs/columns#arbitrary-values). We'll need to use a combination of width-based columns (using the `ch` unit for setting how many characters to visually fit per column at a minimum) and a max of column numbers.
