### ISSUE TITLE
Add `files_field`.

### ISSUE THREAD

**Issue by andrewculver** [bullet-train-co/bullet_train-fields#43]
We have `file_field`, but it only supports a single file. Would love to add a separate field partial that supports multiple files.

**Comment by gazayas** [comment]
Been looking into this one today and it looks like it wouldn't be too difficult to add `multiple: true` to the file input, but I'm assuming we want to handle these individually by adding/removing a div per each file. I'm thinking we'll need to edit the file Stimulus controller, especially since the file removal logic clears all of the attachments as opposed to one at a time per id.

Will keep looking into this one unless other issues need more attention.

**Comment by ammit** [comment]
We can modify the existing `file_field` partial to also support multiple file uploads. This way we can maintain a 1:1 match with rails native helpers. 

Then to render multiple file uploads we can use - 

<%= render 'shared/fields/file_field', form: form, method: :attachment, **options: {multiple: true}** %>

The caveat is the partial will become huge and difficult to maintain.
